OutfixAdminPanel/Controllers/OrderController.cs
using Newtonsoft.Json;
using Outfix.Commons;
using Outfix.Models;
using Outfix.ViewModels;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;

namespace OutfixAdminPanel.Controllers
{
    public class OrderController : Controller
    {
        private string _apiPath;

        public string ApiPath
        {
            get => _apiPath;
            set => _apiPath = value;
        }
        public OrderController()
        {
            ApiPath = "http://localhost:57791/api/order/";
        }
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ShowAllOrders()
        {
            try
            {
                List<OrderModel> orders = new List<OrderModel>();
                var url = ApiPath;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    //HTTP GET
                    var responseTask = client.GetAsync("GetOrdersList");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        orders = JsonConvert.DeserializeObject<List<OrderModel>>(response);
                    }
                }
                return View(orders);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult ShowOrdersByState(string status)
        {
            try
            {
                List<OrderModel> orders = new List<OrderModel>();
                var url = ApiPath;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    //HTTP GET
                    var responseTask = client.GetAsync("GetOrderList?state=" + status);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        orders = JsonConvert.DeserializeObject<List<OrderModel>>(response);
                    }
                }
                return View("ShowAllOrders", orders);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult OrderDetail(int id)
        {
            try
            {
                WP_Common common = new WP_Common();
                
                CartViewModel cvm = new CartViewModel();
                cvm.Order = common.GetOrderDetails(id);
                cvm.Customer = common.getCustomerDetailsById(cvm.Order.CustomerId);
                return View(cvm);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult ChangeBulkStatus(List<string> ids, string status)
        {
            try
            {

                Message msg = new Message();
                msg.ids = ids;
                msg.status = status;

                List<OrderModel> orders = new List<OrderModel>();
                var stringContent = new StringContent(JsonConvert.SerializeObject(msg), System.Text.Encoding.UTF8, "application/json");
                var url = ApiPath;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    //HTTP GET
                    var responseTask = client.PutAsync("ChangeOrderStatusInBulk", stringContent);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;

                    }
                }
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
    public class Message
    {
        public List<string> ids { get; set; }
        public string status { get; set; }
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}

OutfixAdminPanel/Views/Order/OrderDetail.cshtml
@model Outfix.ViewModels.CartViewModel
@using System.ComponentModel;

@{
    ViewBag.Title = "OrderDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var info = typeof(Outfix.Models.ProductVariationModel).GetProperties();
    int count = 0;
}

<h2>Order #@Model.Order.ID Details</h2>
<h6>Payment via Cash on delivery.</h6>
<div class="container">
    <div class="row">
        <div class="column col-md-4">
            <h5>General</h5>
            <div class="row">
                <div class="col-md-2">
                    <label>Date: </label>
                </div>
                <div class="col-md-10" style="font-size:12px">
                    @DateTime.Now
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <label>Status: </label>
                </div>
                <div class="col-md-10" style="color:blue">
                    <select>
                        <option value="pending" selected="@Model.Order.Status.Equals("pending")">Pending</option>
                        <option value="processing">Processing</option>
                        <option value="dispatched">Dispatched</option>
                        <option value="completed">Completed</option>
                    </select>
                    
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <label>Name: </label>
                </div>
                <div class="col-md-10" style="color:black">
                    @Model.Customer.FirstName @Model.Customer.LastName
                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <h5>Billing</h5>
            @Model.Customer.Address
        </div>
        <div class="column col-md-4">
            <h5>Shipping</h5>
            @Model.Customer.Address
        </div>
    </div>
</div>
<div class="container">
    <h2>Products</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Sr No</th>
                <th>Item Name</th>
                <th>Amount</th>
                <th>Qty</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody id="ReviewList">
            @foreach (var product in Model.Order.Products)
            {
                var variation = product.Variation.FirstOrDefault();

                count += 1;
                string rid = "Review" + count;
                var total = variation.Price * variation.Qty;
                <tr id="@rid">
                    <td>@count</td>
                    <td id="Name">
                        @product.Name
                        <br />
                        @foreach (var property in info)
                        {
                            var minfo = variation.GetType().GetProperty(property.Name);
                            var pval = minfo.GetValue(variation, null);
                            var attribute = property.GetCustomAttributes(typeof(DisplayNameAttribute), true).Cast<DisplayNameAttribute>().FirstOrDefault();
                            string displayName = attribute != null ? attribute.DisplayName : "";
                            if (!string.IsNullOrEmpty(displayName))
                            {
                                if (property.PropertyType.Name.Equals("Int32"))
                                {
                                    if (pval != null && Convert.ToInt32(pval) != 0)
                                    {
                                        <span>@displayName: </span>
                                        <span><b>@pval &nbsp;</b></span>
                                    }
                                }
                                else if (property.PropertyType.Name.Equals("Decimal"))
                                {
                                    if (pval != null && Convert.ToDecimal(pval) != 0)
                                    {
                                        <span>@displayName: </span>
                                        <span><b>@pval &nbsp;</b></span>
                                    }
                                }
                                else if (pval != null && !String.IsNullOrEmpty(Convert.ToString(pval)))
                                {
                                    <span>@displayName: </span>
                                    <span><b>@pval &nbsp;</b></span>
                                }
                            }
                        }
                    </td>
                    <td id="ProductId">@variation.Price</td>
                    <td id="ReviewDate">@variation.Qty</td>
                    <td id="Status">@total</td>
                    <td id="Id" hidden>@product.ID</td>
                </tr>
            }
        </tbody>
    </table>
</div>

OutfixAdminPanel/Views/Order/ShowAllOrders.cshtml
@model List<Outfix.Models.OrderModel>

@{
    ViewBag.Title = "ShowAllOrders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Orders</h2>
<p>Manage all orders from here</p>

<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#All" role="tab">All</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#Pending" role="tab">Pending</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#Processing" role="tab">Processing</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#Delivered" role="tab">Delivered</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="row">
        <div class="column col-md-6">
            <div class="row">
                <div class="column col-md-4">
                    <select class="form-control" id="selectOrderState">
                        <option>Change Status</option>
                        <option>Pending</option>
                        <option>Processing</option>
                        <option>Delivered</option>
                        <option>Cancel Order</option>
                    </select>
                </div>
                <div class="column col-md-2">
                    <input class="btn btn-success" type="button" value="Submit" id="btn_select" name="btn_select" />
                </div>
            </div>
        </div>
        <div class="column col-md-6">
            <div class="row">
                <div class="column col-md-3">
                    <label style="padding-top:5px">Search Order</label>
                </div>
                <div class="column col-md-3">
                    <input type="text" id="searchOrder" placeholder="Search Order" />
                </div>
            </div>
        </div>
    </div>
    <div class="tab-pane active" id="All" role="tabpanel">
        <div class="container">

            <table id="tblOrders" class="table table-striped">
                <thead>
                    <tr>
                        <th>Select</th>
                        <th>Order</th>
                        <th>Date</th>
                        <th>Total Qty</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody id="ReviewList">
                    @foreach (var order in Model)
                    {
                        string rid = "Review" + order.ID;
                        <tr id="@rid">
                            <td><input type="checkbox" id="SelectOrder" /></td>
                            <td id="Name" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">#@order.ID  ~  @order.CustomerName</td>
                            <td id="ReviewText" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">@DateTime.Now</td>
                            <td id="ProductId" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">@order.TotalItems</td>
                            <td id="ReviewDate" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">@order.NetPayable</td>
                            <td id="Status" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">@order.Status</td>
                            <td id="Id" hidden>@order.ID</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="tab-pane" id="Pending" role="tabpanel">
        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Select</th>
                        <th>Order</th>
                        <th>Date</th>
                        <th>Total Qty</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody id="ReviewList">
                    @foreach (var order in Model)
                    {
                        if (order.Status.Equals("Pending"))
                        {
                            string rid = "Review" + order.ID;
                            <tr id="@rid" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">
                                <td><input type="checkbox" id="SelectOrder" /></td>
                                <td id="Name">#@order.ID  ~  @order.CustomerName</td>
                                <td id="ReviewText">@DateTime.Now</td>
                                <td id="ProductId">@order.TotalItems</td>
                                <td id="ReviewDate">@order.NetPayable</td>
                                <td id="Status">@order.Status</td>
                                <td id="Id" hidden>@order.ID</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="tab-pane" id="Processing" role="tabpanel">
        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Select</th>
                        <th>Order</th>
                        <th>Date</th>
                        <th>Total Qty</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody id="ReviewList">
                    @foreach (var order in Model)
                    {
                        if (order.Status.Equals("Processing"))
                        {
                            string rid = "Review" + order.ID;
                            <tr id="@rid" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">
                                <td><input type="checkbox" id="SelectOrder" /></td>
                                <td id="Name">#@order.ID  ~  @order.CustomerName</td>
                                <td id="ReviewText">@DateTime.Now</td>
                                <td id="ProductId">@order.TotalItems</td>
                                <td id="ReviewDate">@order.NetPayable</td>
                                <td id="Status">@order.Status</td>
                                <td id="Id" hidden>@order.ID</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="tab-pane" id="Delivered" role="tabpanel">
        <div class="container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Select</th>
                        <th>Order</th>
                        <th>Date</th>
                        <th>Total Qty</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody id="ReviewList">
                    @foreach (var order in Model)
                    {
                        if (order.Status.Equals("Delivered"))
                        {
                            string rid = "Review" + order.ID;
                            <tr id="@rid" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">
                                <td><input type="checkbox" id="SelectOrder" /></td>
                                <td id="Name">#@order.ID  ~  @order.CustomerName</td>
                                <td id="ReviewText">@DateTime.Now</td>
                                <td id="ProductId">@order.TotalItems</td>
                                <td id="ReviewDate">@order.NetPayable</td>
                                <td id="Status">@order.Status</td>
                                <td id="Id" hidden>@order.ID</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



<script src="~/Scripts/Order/ManageOrder.js"></script>