OutfixAdminPanel/Controllers/CustomerController.cs
using Newtonsoft.Json;
using Outfix.Commons;
using Outfix.Models;
using Outfix.ViewModels;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;

namespace OutfixAdminPanel.Controllers
{
    public class CustomerController : Controller
    {
        private string _apiPath;

        public string ApiPath
        {
            get => _apiPath;
            set => _apiPath = value;
        }
        public CustomerController()
        {
            ApiPath = "http://localhost/api/customer/";
        }
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ShowAllCustomers()
        {
            try
            {
                List<CustomerModel> customers = new List<CustomerModel>();
                var url = ApiPath;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    //HTTP GET
                    var responseTask = client.GetAsync("GetCustomerList");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        customers = JsonConvert.DeserializeObject<List<CustomerModel>>(response);
                    }
                }
                return View(customers);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CustomerDetail(string id)
        {
            try
            {
                int cid = Convert.ToInt32(id);
                WP_Common commons = new WP_Common();
                List<OrderModel> orders = new List<OrderModel>();

                var customer = commons.getCustomerDetailsById(cid);
                orders = commons.getCustomerOrders(cid);
                var wallet = commons.getCustomerWallet(cid);

                CustomerDetailViewModel vm = new CustomerDetailViewModel();
                vm.Customer = customer;
                vm.Orders = orders;
                vm.Wallet = wallet;

                return View(vm);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

OutfixAdminPanel/Controllers/WalletController.cs
using Newtonsoft.Json;
using Outfix.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;

namespace OutfixAdminPanel.Controllers
{
    public class WalletController : Controller
    {
        private string _apiPath;

        public string ApiPath
        {
            get => _apiPath;
            set => _apiPath = value;
        }
        public WalletController()
        {
            ApiPath = "http://localhost/api/wallet/";

        }
        // GET: Wallet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowAllWallets()
        {
            try
            {
                List<WalletModel> reviews = new List<WalletModel>();
                var url = ApiPath;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    //HTTP GET
                    var responseTask = client.GetAsync("GetAllWallet");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        reviews = JsonConvert.DeserializeObject<List<WalletModel>>(response);
                    }
                }
                return View(reviews);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult WalletDetail(string id)
        {
            try
            {
                List<WalletDetailsModel> wd = new List<WalletDetailsModel>();
                var url = ApiPath;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    //HTTP GET
                    var responseTask = client.GetAsync("GetWalletByWalletId?WalletId=" + id);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        wd = JsonConvert.DeserializeObject<List<WalletDetailsModel>>(response);
                    }
                }
                return View(wd);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

OutfixAdminPanel/Views/Customer/CustomerDetail.cshtml
@model Outfix.ViewModels.CustomerDetailViewModel
@{
    ViewBag.Title = "CustomerDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int count = 0;
}

<div class="container">
    <div class="row">
        <div class="column col-md-6">
            <h5>General</h5>
            <div class="row">
                <div class="col-md-2">
                    <label>Name: </label>
                </div>
                <div class="col-md-10">
                    @Model.Customer.FirstName @Model.Customer.LastName
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <label>Status: </label>
                </div>
                <div class="col-md-10" style="color:blue">
                    Active
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <label>Address: </label>
                </div>
                <div class="col-md-10" style="color:black">
                    @{
                        var address = Model.Customer.Address;
                        address += Model.Customer.City != null ? ", " + Model.Customer.City : "";
                        address += Model.Customer.Country != null ? ", " + Model.Customer.Country : "";
                    }
                    @address
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <label>Contact: </label>
                </div>
                <div class="col-md-10" style="color:black">
                    @{
                        var contact = Model.Customer.Contact1;
                        contact += Model.Customer.Contact2 != null ? ", " + Model.Customer.Contact2 : "";
                    }
                    @contact
                </div>
            </div>
        </div>
        <div class="column col-md-6">
            <h5>Wallet Details</h5>
            <div class="row">
                <div class="col-md-2">
                    <label>Credit: </label>
                </div>
                <div class="col-md-2" style="color:black">
                    @Model.Wallet.Credit
                </div>
                <div class="col-md-8" style="color:black">
                    <span class="col-md-2 fa fa-history" id="walletHistory" title="Wallet History" onclick="location.href = '@Url.Action("WalletDetail", "Wallet", new { id = Model.Wallet.ID })'"></span>
                    <span class="col-md-2 fa fa-gift" id="reimburse" title="Reimbursed Credit"></span>
                    <div class="col-md-8" id="divReimburse" style="display:none" >
                        <input id="txtReimburse" placeholder="Enter Amount" style="width:120px"/>
                        <input id="btnReimburse" type="button" value="Save" /> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <h2>Order Detail</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Sr No</th>
                <th>Order Id</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody id="ReviewList">
            @foreach (var order in Model.Orders)
            {
                count += 1;
                string rid = "Order" + count;
                <tr id="@rid" onclick="location.href = '@Url.Action("OrderDetail", "Order", new { id = order.ID })'">
                    <td>@count</td>
                    <td id="Name">@order.ID</td>
                    <td id="Date">@order.CreatedDate</td>
                    <td id="Amount">@order.NetPayable</td>
                    <td id="Status">@order.Status</td>
                    <td id="Id" hidden>@order.ID</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script src="~/Scripts/Customer/Customer.js"></script>

OutfixAdminPanel/Views/Customer/ShowAllCustomers.cshtml
@model List<Outfix.Models.CustomerModel>

@{
    ViewBag.Title = "ShowAllCustomers";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int count = 0;
}

<div class="container">
    <h2>Users</h2>
    <p>Manage all Users from here</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Sr No</th>
                <th>Name</th>
                <th>Email</th>
                <th>Gender</th>
                <th>City</th>
                <th>Country</th>
                <th>State</th>
            </tr>
        </thead>
        <tbody id="ReviewList">
            @foreach (var customer in Model)
            {
                count += 1;
                string rid = "Customer" + count;
                <tr id="@rid" onclick="location.href = '@Url.Action("CustomerDetail", "Customer", new { id = customer.ID })'">
                    <td>@count</td>
                    <td id="Name">@customer.FirstName @customer.LastName</td>
                    <td id="ProductId">@customer.Email</td>
                    <td id="ReviewText">@customer.Gender</td>
                    <td id="ReviewText">@customer.City</td>
                    <td id="ReviewText">@customer.Country</td>
                    <td id="ReviewText">@customer.IsActive</td>
                    <td id="Id" hidden>@customer.ID</td>
                </tr>
            }
        </tbody>
    </table>
</div>