OutfixAdminPanel/Controllers/ReferralController.cs
using Newtonsoft.Json;
using Outfix.Models;
using Outfix.ViewModels;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;

namespace OutfixAdminPanel.Controllers
{
    public class ReferralController : Controller
    {
        private string _apiPath;

        public string ApiPath
        {
            get => _apiPath;
            set => _apiPath = value;
        }
        public ReferralController()
        {
            ApiPath = "http://localhost/api/referral/";

        }
        // GET: Referral
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowAllReferrals()
        {
            try
            {
                List<ReferralModel> referrals = new List<ReferralModel>();
                var url = ApiPath;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    //HTTP GET
                    var responseTask = client.GetAsync("GetReferralList");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        referrals = JsonConvert.DeserializeObject<List<ReferralModel>>(response);
                    }
                }
                return View(referrals);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ReferralDetail(string id)
        {
            try
            {
                ReferralModel referral = new ReferralModel();
                List<ReferralDetailsModel> details = new List<ReferralDetailsModel>();
                var url = ApiPath;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    
                    //HTTP GET
                    var responseTask = client.GetAsync("GetReferralDetailsList?ReferralId=" + Convert.ToInt32(id));
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        details = JsonConvert.DeserializeObject<List<ReferralDetailsModel>>(response);
                    }

                    responseTask = client.GetAsync("GetReferralById?Id=" + Convert.ToInt32(id));
                    responseTask.Wait();

                    result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        referral = JsonConvert.DeserializeObject<ReferralModel>(response);
                    }
                    
                }

                ReferralViewModel vm = new ReferralViewModel();
                vm.Referral = referral;
                vm.ReferralDetails = details;

                return View(vm);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CreateReferral()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateReferralForUser(ReferralModel model)
        {
            try
            {
                List<ReferralModel> referrals = new List<ReferralModel>();
                var url = ApiPath;
                var stringContent = new StringContent(model.ToString(), System.Text.Encoding.UTF8, "application/json");
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    //HTTP GET
                    var responseTask = client.PostAsync("CreateReferralForUser", stringContent);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();

                        var response = readTask.Result;
                        // referrals = JsonConvert.DeserializeObject<List<ReferralModel>>(response);
                    }
                }
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

OutfixAdminPanel/Views/Referral/CreateReferral.cshtml
@model Outfix.Models.ReferralModel
@{
    ViewBag.Title = "CreateReferral";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Create Referral</h3>
<h6>Create and Manage referral codes for Any User</h6>

@using (Html.BeginForm("CreateReferralForUser", "Referral", FormMethod.Post))
{
    <div class="container">
        <div class="row form-group">
            <div class="col col-md-2">
                @Html.LabelFor(m => m.Code)
            </div>
            <div class="col col-md-4">
                @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col col-md-2">
                @Html.LabelFor(m => m.Name)
            </div>
            <div class="col col-md-4">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col col-md-2">
                @Html.LabelFor(m => m.Description)
            </div>
            <div class="col col-md-4">
                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col col-md-2">
                @Html.LabelFor(m => m.Limit)
            </div>
            <div class="col col-md-4">
                @Html.TextBoxFor(m => m.Limit, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col col-md-2">
                @Html.LabelFor(m => m.WalletPoints)
            </div>
            <div class="col col-md-4">
                @Html.TextBoxFor(m => m.WalletPoints, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col col-md-2">
                @Html.LabelFor(m => m.UserId)
            </div>
            <div class="col col-md-4">
                @Html.TextBoxFor(m => m.UserId, new { @class = "form-control" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col col-md-6">
                <input type="submit" class="btn btn-success" value="Submit" style="float:right" />
            </div>
        </div>
    </div>
}

OutfixAdminPanel/Views/Referral/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

OutfixAdminPanel/Views/Referral/ReferralDetail.cshtml
@model Outfix.ViewModels.ReferralViewModel
@{
    ViewBag.Title = "ReferralDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int count = 0;
}


<div class="container">
    <div class="row">
        <div class="column col-md-4">
            <h5><u>General</u></h5>
            <div class="row">
                <div class="col-md-4">
                    <label>Date: </label>
                </div>
                <div class="col-md-8">
                    @DateTime.Now
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <label>Status: </label>
                </div>
                <div class="col-md-8" style="color:blue">
                    Active
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <label>Name: </label>
                </div>
                <div class="col-md-8" style="color:black">
                    @Model.Referral.Name
                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <h5><u>Wallet Details</u></h5>
            <div class="row">
                <div class="col-md-4">
                    <label>Points: </label>
                </div>
                <div class="col-md-8">
                    @Model.Referral.WalletPoints
                </div>
            </div>
        </div>
        <div class="column col-md-4">
            <h5><u>Usage</u></h5>
            <div class="row">
                <div class="col-md-4">
                    <label>Total Limit</label>
                </div>
                <div class="col-md-8">
                    @Model.Referral.Limit
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <h2>Referral Detail</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Sr No</th>
                <th>Order Id</th>
                <th>User</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody id="ReviewList">
            @foreach (var referral in Model.ReferralDetails)
            {
                count += 1;
                string rid = "Referral" + count;
                <tr id="@rid">
                    <td>@count</td>
                    <td id="Name">@referral.OrderId</td>
                    <td id="ReviewDate">@referral.UserId</td>
                    <td id="ProductId">@referral.WalletPoints</td>
                    <td id="Id" hidden>@referral.ReferralId</td>
                </tr>
            }
        </tbody>
    </table>
</div>

OutfixAdminPanel/Views/Referral/ShowAllReferrals.cshtml
@model List<Outfix.Models.ReferralModel>

@{
    ViewBag.Title = "ShowAllReferrals";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int count = 0;
}

<div class="container">
    <h2>Referral Codes</h2>
    <p>Manage all Referral Codes from here</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Sr No</th>
                <th>Referal Code</th>
                <th>Name</th>
                <th>Description</th>
                <th>Limit</th>
                <th>User Id</th>
            </tr>
        </thead>
        <tbody id="ReviewList">
            @foreach (var referral in Model)
            {
                count += 1;
                string rid = "Review" + count;
                <tr id="@rid" onclick="location.href = '@Url.Action("ReferralDetail", "Referral", new { id = referral.ID })'">
                    <td>@count</td>
                    <td id="Name">@referral.Code</td>
                    <td id="ReviewText">@referral.Name</td>
                    <td id="ProductId">@referral.Description</td>
                    <td id="ProductId">@referral.Limit</td>
                    <td id="ReviewDate">@referral.UserId</td>
                    <td id="Id" hidden>@referral.ID</td>
                </tr>
            }
        </tbody>
    </table>
</div>