Outfix.WebAppPortal/Controllers/ProductController.cs
using Outfix.Commons;
using Outfix.Models;
using Outfix.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace Outfix.WebAppPortal.Controllers
{
    public class ProductController : Controller
    {
        WP_Common common = new WP_Common();
        private static List<ProductModel> products;

        public static List<ProductModel> Products
        {
            get => products;
            set => products = value;
        }

        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductsPage(SearchFilterModel search = null)
        {
            ViewBag.Hierarchy = common.setHierarchy(search);
            if (search != null)
            {
                ViewBag.SideFilters = search;
            }

            var path = ConfigurationManager.AppSettings["ServerPath"].ToString();

            List<ProductModel> products = new List<ProductModel>();

            if (string.IsNullOrEmpty(search.search_input))
            {
                Products = common.getAllProducts(search);
            }
            else
            {
                Products = common.getProductbySearch(search.search_input);
            }
            Products.ForEach(x =>
            {
                //x = common.getProductWithVariationById(x.ItemCode);

                //x.Cart.Pic = string.IsNullOrEmpty(x.Picture1) ? "" : Path.Combine(path, x.Picture1);

                x.Picture1 = string.IsNullOrEmpty(x.Picture1) ? "" : Path.Combine(path, x.Picture1);
                x.Picture2 = string.IsNullOrEmpty(x.Picture2) ? "" : Path.Combine(path, x.Picture2);
                x.Picture3 = string.IsNullOrEmpty(x.Picture3) ? "" : Path.Combine(path, x.Picture3);
                x.Picture4 = string.IsNullOrEmpty(x.Picture4) ? "" : Path.Combine(path, x.Picture4);
                x.Picture5 = string.IsNullOrEmpty(x.Picture5) ? "" : Path.Combine(path, x.Picture5);
                x.Variation.ForEach(y => y.Picture = string.IsNullOrEmpty(y.Picture) ? "" : Path.Combine(path, y.Picture));
            });

            return View(Products);
        }

        public ActionResult ShowFilters(SearchFilterModel search)
        {
            ViewBag.SideFilters = search;

            var Filters = common.getAllFilters();
            return View(Filters);
        }
        public ActionResult ProductsDetailsPage(string id)
        {
            try
            {
                if (id == null)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }
                var path = ConfigurationManager.AppSettings["ServerPath"].ToString();

                ProductDetailViewModel model = new ProductDetailViewModel();
                model.Product = common.getProductWithVariationById(id);
                if (model.Product != null)
                {

                    model.Reviews = common.getProductReviews(id);

                    model.Product.Picture1 = string.IsNullOrEmpty(model.Product.Picture1) ? "" : Path.Combine(path, model.Product.Picture1);
                    model.Product.Picture2 = string.IsNullOrEmpty(model.Product.Picture2) ? "" : Path.Combine(path, model.Product.Picture2);
                    model.Product.Picture3 = string.IsNullOrEmpty(model.Product.Picture3) ? "" : Path.Combine(path, model.Product.Picture3);
                    model.Product.Picture4 = string.IsNullOrEmpty(model.Product.Picture4) ? "" : Path.Combine(path, model.Product.Picture4);
                    model.Product.Picture5 = string.IsNullOrEmpty(model.Product.Picture5) ? "" : Path.Combine(path, model.Product.Picture5);
                    model.Product.Variation.ForEach(y => y.Picture = string.IsNullOrEmpty(y.Picture) ? "" : Path.Combine(path, y.Picture));
                    //model.Product.Cart.Pic = string.IsNullOrEmpty(model.Product.Cart.Pic) ? "" : Path.Combine(path, model.Product.Cart.Pic);


                    var search = new SearchFilterModel
                    {
                        Ct = model.Product.MainCategory,
                        SCt = model.Product.SubCategory,
                        Bd = model.Product.Brand,
                    };
                    ViewBag.Hierarchy = common.setHierarchy(search);

                    if (Session["VariationValues"] != null)
                    {
                        Session.Remove("VariationValues");
                    }
                }

                return View(model);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml", ex);
            }
        }
        public ActionResult SimilarProducts(string ic)
        {
            var path = ConfigurationManager.AppSettings["ServerPath"].ToString();
            var model = common.getSimilarProducts(ic);
            model.ForEach(x =>
            {
                x.Picture1 = string.IsNullOrEmpty(x.Picture1) ? "" : Path.Combine(path, x.Picture1);
            });
            return View(model);
        }
        public ActionResult searchProduct(string str, string device = "web")
        {
            var names = common.getNamesbySearch(str);
            ViewBag.search = device;
            return View("SearchResults", names);
        }

        public ActionResult getDDLs(string ids, string itemcode, string field, string value)
        {
            List<ProductVariationModel> VariationValues;
            ProductVariationModel Variation;

            if (Session["VariationValues"] != null)
            {
                VariationValues = (List<ProductVariationModel>)Session["VariationValues"];
                Variation = VariationValues.FirstOrDefault(x => x.ProductId == itemcode);
                if (Variation == null)
                {
                    Variation = new ProductVariationModel();

                    Variation.ProductId = itemcode;
                    Variation.GetType().GetProperty(field).SetValue(Variation, value);
                    VariationValues.Add(Variation);
                }
                else
                {
                    Variation.GetType().GetProperty(field).SetValue(Variation, value);
                }
            }
            else
            {
                VariationValues = new List<ProductVariationModel>();
                Variation = new ProductVariationModel();

                Variation.ProductId = itemcode;
                Variation.GetType().GetProperty(field).SetValue(Variation, value);
                VariationValues.Add(Variation);

            }

            Session["VariationValues"] = VariationValues;
            var model = common.getVariationDropDowns(ids);

            var path = ConfigurationManager.AppSettings["ServerPath"].ToString();
            model.ForEach(x => x.Picture = string.IsNullOrEmpty(x.Picture) ? "" : Path.Combine(path, x.Picture));

            return View("ProductVariations", model);
        }

        public ActionResult ProductVariations(List<ProductVariationModel> p)
        {
            return View(p);
        }
        [HttpPost]
        public ActionResult ProductIFrame(string id)
        {
            ProductDetailViewModel model = new ProductDetailViewModel();
            model.Product = common.getProductWithVariationById(id);

            var path = ConfigurationManager.AppSettings["ServerPath"].ToString();
            //p.ForEach(y => y.Picture = string.IsNullOrEmpty(y.Picture) ? "" : Path.Combine(path, y.Picture));
            return View(model);
        }
        //public ActionResult clearDDLs(string itemcode, string field)
        //{
        //    List<ProductVariationModel> VariationValues;
        //    ProductVariationModel Variation;

        //    if (Session["VariationValues"] != null)
        //    {
        //        VariationValues = (List<ProductVariationModel>)Session["VariationValues"];
        //        Variation = VariationValues.FirstOrDefault(x => x.ProductId == itemcode);
        //        if (Variation == null)
        //        {
        //            Variation = new ProductVariationModel();
        //            Variation.ProductId = itemcode;
        //            Variation.GetType().GetProperty(field).SetValue(Variation, null);
        //            VariationValues.Add(Variation);
        //        }
        //        else
        //        {
        //            Variation.GetType().GetProperty(field).SetValue(Variation, null);
        //        }
        //    }
        //    else
        //    {
        //        VariationValues = new List<ProductVariationModel>();
        //        Variation = new ProductVariationModel();

        //        Variation.ProductId = itemcode;
        //        Variation.GetType().GetProperty(field).SetValue(Variation, null);
        //        VariationValues.Add(Variation);

        //    }

        //    Session["VariationValues"] = VariationValues;
        //    var model = common.getVariationDropDowns(ids);

        //    var path = ConfigurationManager.AppSettings["ServerPath"].ToString();
        //    model.ForEach(x => x.Picture = string.IsNullOrEmpty(x.Picture) ? "" : Path.Combine(path, x.Picture));

        //    return View("ProductVariations", model);
        //}
        public ActionResult clearAllDDLs(string Code)
        {
            if (Session["VariationValues"] != null)
            {
                Session.Remove("VariationValues");
            }

            var model = common.getProductWithVariationById(Code);
            var path = ConfigurationManager.AppSettings["ServerPath"].ToString();
            model.Variation.ForEach(x => x.Picture = string.IsNullOrEmpty(x.Picture) ? "" : Path.Combine(path, x.Picture));
            return View("ProductVariations", model.Variation);
        }
    }
}

Outfix.WebAppPortal/Controllers/ProfileController.cs
using Facebook;
using Newtonsoft.Json;
using Outfix.Commons;
using Outfix.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace Outfix.WebAppPortal.Controllers
{
    public class ProfileController : Controller
    {
        WP_Common commons;
        StyleProfileSurveyModel surveyCust;
        public ProfileModel profile { get; set; }

        public ProfileController()
        {

        }
        // GET: Profile
        public ActionResult Index()
        {
            commons = new WP_Common();
            var customer = (CustomerModel)Session["Customer"];
            profile = new ProfileModel();
            if (customer != null)
            {
                surveyCust = new StyleProfileSurveyModel();
            }

            surveyCust.Customer = customer;
            var srv = commons.GetSurveyForUser(surveyCust);

            profile.StyleProfile = commons.getAllQuestionAnswers();
            profile.Customer = customer;
            profile.UserAnswers = srv;
            //profile.ReferCode = commons.getCustomerReferCode(customer.ID);
            //shareToFb();
            return View(profile);
        }

        public ActionResult Refer()
        {
            commons = new WP_Common();
            var customer = (CustomerModel)Session["Customer"];
            profile = new ProfileModel();
            profile.Customer = customer;
            
            return View(profile);
        }

        public ActionResult OrderReview(int id)
        {
            commons = new WP_Common();
            var path = ConfigurationManager.AppSettings["ServerPath"].ToString();
            var customer = (CustomerModel)Session["Customer"];
            profile = new ProfileModel();
            profile.Customer = customer;
            profile.Customer.Orders = new List<OrderModel>();
            var order = commons.GetOrderDetails(id);
            order.Products.ForEach(y => y.Picture1 = string.IsNullOrEmpty(y.Variation.FirstOrDefault().Picture) ? "" : Path.Combine(path, y.Variation.FirstOrDefault().Picture));
            profile.Customer.Orders.Add(order);
            
            return View(profile);
        }
        public ActionResult OrderHistory()
        {
            var path = ConfigurationManager.AppSettings["ServerPath"].ToString();

            commons = new WP_Common();
            var customer = (CustomerModel)Session["Customer"];
            profile = new ProfileModel();
            profile.Customer = customer;
            profile.Customer.Orders = commons.getCustomerOrders(customer.ID);
            profile.Customer.Orders.ForEach(y =>
            {
                y.Products.ForEach(x =>
                {
                    x.Picture1 = string.IsNullOrEmpty(x.Picture1) ? "" : Path.Combine(path, x.Picture1);
                });
            });
            return View(profile);
        }
        [HttpPost]
        public void SaveSurveyForm(String str)
        {
            commons = new WP_Common();
            var Survey = JsonConvert.DeserializeObject<List<StyleProfileUserAnswersModel>>(str);
            var Cust = (CustomerModel)(Session["Customer"]);
            surveyCust = new StyleProfileSurveyModel();
            surveyCust.Customer = Cust;
            surveyCust.survey = Survey;
            commons.CreateSurveyForUser(surveyCust);

        }
        [HttpGet]
        public void GetSurveyForm()
        {
            commons = new WP_Common();
            var Cust = (CustomerModel)(Session["Customer"]);
            surveyCust = new StyleProfileSurveyModel();
            surveyCust.Customer = Cust;
            commons.GetSurveyForUser(surveyCust);

        }

        public void shareToFb()
        {
            var fbtoken = "";
            if(Session["AuthIdFb"] != null)
            {
                fbtoken = Session["AuthIdFb"].ToString();
            }
            dynamic messagePost = new ExpandoObject();

            messagePost.name = "Post For Fun"; // "{*actor*} " + "posted news...";
            messagePost.caption = "Hello Guys";
            messagePost.description = "Just for checking";
            messagePost.message = "No hidden Message";
            string acccessToken = "439132446670385|bf3c34a62fd83c2bd2f13e332cb57633";
            var appp = new FacebookClient(acccessToken);
            // Calling Graph API for user info
            dynamic me = appp.Get(fbtoken+"?fields=friends,name,email");
            //dynamic me = appp.Get(fbtoken);

            string id = me.id; // You can store it in the database
            string name = me.name;
            string email = me.email;

            //var client = new FacebookClient("asd");
            var args = new Dictionary<string, object>();
            args["message"] = "Just for checking";

            var path =  id + "/feed";
            try
            {
                //var postId = appp.Post(path + "/feed", messagePost);
                appp.Post(path, args);
            }
            catch (FacebookOAuthException ex)
            { 
                //handle oauth exception } catch (FacebookApiException ex) { //handle facebook exception
            }
        }

        #region [Map]    
        [HttpPost]
        public JsonResult GetMap()
        {
            var data1 = GetMapModel();
            return Json(data1, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UserLocation()
        {
            return View();
        }
        public List<MapModel> GetMapModel()
        {
            var model = new List<MapModel>();
            //return (from p in db.
            //        select new
            //        {
            //            Name = p.Name,
            //            Latitude = p.Latitude,
            //            Longitude = p.Longitude,
            //            Location = p.Location,
            //            Description = p.Description,
            //            Id = p.Id
            //        }).ToList()
            //    .Select(res => new Map
            //    {
            //        Name = res.Name,
            //        Latitude = res.Latitude,
            //        Longitude = res.Longitude,
            //        Location = res.Location,
            //        Description = res.Description,
            //        Id = res.Id


            //    });
            return model;
        }
        #endregion
    }
}

Outfix.WebAppPortal/Views/Home/About.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Outfix - About";
}

<div class="about_div">
    <div class="about" style="margin:auto;padding:20px;color:white;background:#0d567f;text-align:center;width:95%;">
        <h1 style="font-weight:bold;">About Us</h1>
        <p style="font-size:20px;">
            Outfix is a leading firm with a Head office based in the United Kingdom, London along with distinctive presence internationally. The organisation is consisted of experienced professional management team with entirely new concept within the consumer goods industry to save international staff costs and international office expenses.
        </p>
        <h3 style="margin-left:30px;text-align:left;font-weight:bold;">Why Choose Outfix?</h3>
        <p style="margin-left:30px;text-align:left;font-size:18px;">
            We pride ourselves in offering complete customised international Brand Intelligence services and solutions to the UK & Ireland, GCC and Africa.
            Our team are trained and have to meet the benchmarks set by the organisation to ensure that they provide the best brand solutions for their brand to our clients.
        </p>
        <h3 style="margin-left:30px;text-align:left;font-weight:bold;">What we do?</h3>
        <p style="margin-left:30px;text-align:left;font-size:18px;">We are available for advising and guiding our clients throughout the process of <strong>new brand development</strong> in their desired market, aswell as <strong>existing brand development</strong> by re-engineering in the market. We have a team of dedicated professionals working in their areas of expertise with a positive attitude. We take great pride in our staff and have a wonderful team of professionals working for us.</p>
        <ul style="margin-left:30px;text-align:left;font-size:20px;">
            <li>New Brand Development Globally</li>
            <li>Exisitng Brand Development Globally</li>
        </ul>
        <h3 style="margin-left:30px;text-align:left;font-weight:bold;">Our Specialities</h3>
        <p style="margin-left:30px;text-align:left;font-size:18px;">We are interface between the client and the international market.  We are here to <strong>provide the best solution and great services for clients to transform their local brand into an international brand</strong> and increase the existing brand’s market share and profitability by using our entirely unique concepts to save international team costs by hiring our services for us to manage their brand awareness internationally and use our International offices as representative offices to save international office expenses.</p>
    </div>
    <div class="about_1" style="margin:auto;text-align:center;background:white;width:95%;">
        <img class="about_logo" src="~/Content/images/logo.png" />
    </div>
</div>

Outfix.WebAppPortal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Outfix.WebAppPortal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var cust = Session["Customer"] != null && !string.IsNullOrEmpty(Session["Customer"].ToString()) ? Session["Customer"] : null;
}

<div class="container started get_started">
    <button style="margin-top:10px;font-size:20px;" type="button" class="btn start">Get Started&nbsp;&nbsp;<span style="font-size:15px;" class="glyphicon glyphicon-triangle-right"></span></button>
</div>

<div class="main">
    <div class="punchline">
        <h1 class="heading">Breaking the E-Commerce<br>Shopping Experience</h1>
        <p class="tagline">We let you keep what you like<br>and return the rest.</p>
        <button style="font-size:20px;" type="button" class="btn start">Get Started&nbsp;&nbsp;<span style="font-size:15px;" class="glyphicon glyphicon-triangle-right"></span></button>
        <br><a style="color:black;" href="#categories"><span style="font-size:40px;" class="glyphicon glyphicon-menu-down"></span></a>
    </div>
</div>

<div class="container" style="margin-top:70px;width:100%;">
    <div class="row">
        <div id="categories" class="cat1 column">
            <a href="@Url.Action("ProductsPage","Product",new { Tp= "Men" })"><img style="box-shadow: 2px 2px 2px 2px rgba(0, 0, 0, .5);border-radius:5px;" src="~/Content/images/Categories/Men.jpeg"></a>
        </div>
        <div class="cat2 column">
            <a href="@Url.Action("ProductsPage","Product",new { Tp= "Women" })"><img style="box-shadow: 2px 2px 2px 2px rgba(0, 0, 0, .5);border-radius:5px;" src="~/Content/images/Categories/Women.jpeg"></a>
        </div>
        <div class="cat2 column">
            <a href="@Url.Action("ProductsPage","Product",new { Tp="Kids" })"><img style="box-shadow: 2px 2px 2px 2px rgba(0, 0, 0, .5);border-radius:5px;" src="~/Content/images/Categories/Kids.jpeg"></a>
        </div>
    </div>
</div>

<div class="container how_it_works">
    <h1 style="color:white;text-align:center;">How It Works</h1>
    <div style="padding-bottom:40px;" class="row">
        <div class="how1 column">
            <h1 style="text-decoration:underline;color:white;text-align:center;">01</h1>
            <h2 style="font-weight:bold;font-size:20px;color:white;text-align:center;">Select Products</h2>
            <p style="font-size:15px;color:white;text-align:center;">Select a maximum of 8 products per order.</p>
        </div>
        <div class="how2 column">
            <h1 style="text-decoration:underline;color:white;text-align:center;">02</h1>
            <h2 style="font-weight:bold;font-size:20px;color:white;text-align:center;">Buy what you want</h2>
            <p style="font-size:15px;color:white;text-align:center;">Try on pieces at home before you buy, keep your favorites and send back the rest.</p>
        </div>
        <div class="how2 column">
            <h1 style="text-decoration:underline;color:white;text-align:center;">03</h1>
            <h2 style="font-weight:bold;font-size:20px;color:white;text-align:center;">Tell us what you think</h2>
            <p style="font-size:15px;color:white;text-align:center;">Share your experience and give us the feedback on the items you purchased.</p>
        </div>
    </div>
    <div style="margin-bottom:10px;text-align:center;width:100%;height:auto;" class="container">
        <video class="vid sc_video" muted controls autoplay loop>
            <source src="~/Content/images/video.mp4" type="video/mp4">
        </video>
    </div>
</div>

<div class="ready">
    <div class="cont1">
    </div>
    <div class="cont2">
    </div>
    {
    <div class="cont3">
        @if (cust == null)
        {
            <button type="button" data-toggle="modal" data-target="#modalLogin" class="btn ready_button">Take Your Style Quiz&nbsp;&nbsp;<span style="font-size:15px;" class="glyphicon glyphicon-triangle-right"></span></button>
        }
        else
        {
            <button type="button" onclick="location.href = '@Url.Action("Index", "Profile")'" class="btn ready_button">Take Your Style Quiz&nbsp;&nbsp;<span style="font-size:15px;" class="glyphicon glyphicon-triangle-right"></span></button>
        }
        <p style="margin-top:30px;margin-bottom:10px;font-size:18px;">Already Have an Account? <a href="#" data-toggle="modal" data-target="#modalLogin">Sign Up&nbsp;<span style="font-size:15px;" class="glyphicon glyphicon-triangle-right"></span></a></p>
    </div>
    <div class="cont4">
        <h3><b>Ready to Sign Up?</b></h3>
    </div>
</div>

Outfix.WebAppPortal/Views/Home/Register.cshtml
@using Outfix.ViewModels
@model Outfix.ViewModels.RegisterViewModel
@{
    Layout = "~/Views/Shared/_LayoutNoHeaders.cshtml";
    ViewBag.Title = "Register";
    var returnURL = Request.Url != null ? Request.Url.ToString() : "/";
}

<div class="signup_form" id="divRegister" style="width:50%;margin:auto">
    <a href="@Url.Action("Index","Home")">
        <img style="border:none;margin-top:0px;width:50%;" src="~/Content/images/logo.png" />
    </a>
    @using (Html.BeginForm("Register", "Account", new { ReturnUrl = returnURL }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="signup_field" >
            <div style="width:99%;">
                <span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;@Html.TextBoxFor(m => m.Username, new { style = "width:90%;font-size:15px;margin-top:10px;border-radius:5px;", placeholder = "Username" })
                <span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;@Html.TextBoxFor(m => m.Email, new { style = "width:90%;font-size:15px;margin-top:10px;border-radius:5px;", placeholder = "Email" })
            </div>
            <div style="width:99%;">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;&nbsp;@Html.PasswordFor(m => m.Password, new { style = "width:90%;font-size:15px;margin-top:10px;border-radius:5px;", placeholder = "Password" })
                @Html.PasswordFor(m => m.ConfirmPassword, new { style = "margin-left:20px;width:90%;font-size:15px;margin-top:10px;border-radius:5px;", placeholder = "Confirm Password" })
            </div>
        </div>
        <div style="width:100%;text-align:center;">
            <span class="glyphicon glyphicon-link"></span>&nbsp;&nbsp;@Html.TextBoxFor(m => m.Refferal, new { style = "width:50%;font-size:15px;margin-top:10px;border-radius:5px;", placeholder = "Referral (if any)" })
            <br />
            <input style="margin-top:15px;font-size:20px" class="btn checkout" type="submit" name="Validate" value="Sign Up" />
        </div>
    }
</div>